version: '1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: KittyFacts
    depends_on:
      - db
    environment:
      - SPRING_PROFILE = prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/camunda
      - SPRING_DATASOURCE_USERNAME=camunda
      - SPRING_DATASOURCE_PASSWORD=1511
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - PORT = 8080
      - MAIL_USER = 1111
      - MAIL_PASSWORD = 1111

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=camunda
      - POSTGRES_PASSWORD=1511